import scripts.pong.strategy as strategy

# Pong
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080
TARGET_RESPAWN_TIME = 2000
MIN_DISTANCE_TARGET = 400
TIME_TO_STOP_PLAYER = 2000
TIME_TO_CATCH_PER_PIXEL = 10
SHOW_SCORE = True
USED_STRATEGY_CLASS = strategy.KeyStrategy
MIN_DURATION_OF_TRIAL = 1
OBJECT_SIZE = 14

# Calibration
CALIBRATION_WAIT_TIMER = 3
BLACK_WINDOW_TIMER = 3
FOCUS_POINT_TIMER = 3

# Loader
NOTCH_FILTER_FREQ: float = 50
NOTCH_FILTER = True


